export interface SurahMeta {
  id: number;
  nameEn: string;
  nameAr: string;
  ayahs: number;
  type: "makki" | "madani";
}

export const SURAHS: SurahMeta[] = [
  { id: 1, nameEn: "Al-Fatihah", nameAr: "الفاتحة", ayahs: 7, type: "makki" },
  { id: 2, nameEn: "Al-Baqarah", nameAr: "البقرة", ayahs: 286, type: "madani" },
  { id: 3, nameEn: "Aal Imran", nameAr: "آل عمران", ayahs: 200, type: "madani" },
  { id: 4, nameEn: "An-Nisa", nameAr: "النساء", ayahs: 176, type: "madani" },
  { id: 5, nameEn: "Al-Ma'idah", nameAr: "المائدة", ayahs: 120, type: "madani" },
  { id: 6, nameEn: "Al-An'am", nameAr: "الأنعام", ayahs: 165, type: "makki" },
  { id: 7, nameEn: "Al-A'raf", nameAr: "الأعراف", ayahs: 206, type: "makki" },
  { id: 8, nameEn: "Al-Anfal", nameAr: "الأنفال", ayahs: 75, type: "madani" },
  { id: 9, nameEn: "At-Tawbah", nameAr: "التوبة", ayahs: 129, type: "madani" },
  { id: 10, nameEn: "Yunus", nameAr: "يونس", ayahs: 109, type: "makki" },
  { id: 11, nameEn: "Hud", nameAr: "هود", ayahs: 123, type: "makki" },
  { id: 12, nameEn: "Yusuf", nameAr: "يوسف", ayahs: 111, type: "makki" },
  { id: 13, nameEn: "Ar-Ra'd", nameAr: "الرعد", ayahs: 43, type: "madani" },
  { id: 14, nameEn: "Ibrahim", nameAr: "إبراهيم", ayahs: 52, type: "makki" },
  { id: 15, nameEn: "Al-Hijr", nameAr: "الحجر", ayahs: 99, type: "makki" },
  { id: 16, nameEn: "An-Nahl", nameAr: "النحل", ayahs: 128, type: "makki" },
  { id: 17, nameEn: "Al-Isra", nameAr: "الإسراء", ayahs: 111, type: "makki" },
  { id: 18, nameEn: "Al-Kahf", nameAr: "الكهف", ayahs: 110, type: "makki" },
  { id: 19, nameEn: "Maryam", nameAr: "مريم", ayahs: 98, type: "makki" },
  { id: 20, nameEn: "Ta-Ha", nameAr: "طه", ayahs: 135, type: "makki" },
  { id: 21, nameEn: "Al-Anbiya", nameAr: "الأنبياء", ayahs: 112, type: "makki" },
  { id: 22, nameEn: "Al-Hajj", nameAr: "الحج", ayahs: 78, type: "madani" },
  { id: 23, nameEn: "Al-Mu'minun", nameAr: "المؤمنون", ayahs: 118, type: "makki" },
  { id: 24, nameEn: "An-Nur", nameAr: "النور", ayahs: 64, type: "madani" },
  { id: 25, nameEn: "Al-Furqan", nameAr: "الفرقان", ayahs: 77, type: "makki" },
  { id: 26, nameEn: "Ash-Shu'ara", nameAr: "الشعراء", ayahs: 227, type: "makki" },
  { id: 27, nameEn: "An-Naml", nameAr: "النمل", ayahs: 93, type: "makki" },
  { id: 28, nameEn: "Al-Qasas", nameAr: "القصص", ayahs: 88, type: "makki" },
  { id: 29, nameEn: "Al-Ankabut", nameAr: "العنكبوت", ayahs: 69, type: "makki" },
  { id: 30, nameEn: "Ar-Rum", nameAr: "الروم", ayahs: 60, type: "makki" },
  { id: 31, nameEn: "Luqman", nameAr: "لقمان", ayahs: 34, type: "makki" },
  { id: 32, nameEn: "As-Sajdah", nameAr: "السجدة", ayahs: 30, type: "makki" },
  { id: 33, nameEn: "Al-Ahzab", nameAr: "الأحزاب", ayahs: 73, type: "madani" },
  { id: 34, nameEn: "Saba", nameAr: "سبأ", ayahs: 54, type: "makki" },
  { id: 35, nameEn: "Fatir", nameAr: "فاطر", ayahs: 45, type: "makki" },
  { id: 36, nameEn: "Ya-Sin", nameAr: "يس", ayahs: 83, type: "makki" },
  { id: 37, nameEn: "As-Saffat", nameAr: "الصافات", ayahs: 182, type: "makki" },
  { id: 38, nameEn: "Sad", nameAr: "ص", ayahs: 88, type: "makki" },
  { id: 39, nameEn: "Az-Zumar", nameAr: "الزمر", ayahs: 75, type: "makki" },
  { id: 40, nameEn: "Ghafir", nameAr: "غافر", ayahs: 85, type: "makki" },
  { id: 41, nameEn: "Fussilat", nameAr: "فصلت", ayahs: 54, type: "makki" },
  { id: 42, nameEn: "Ash-Shura", nameAr: "الشورى", ayahs: 53, type: "makki" },
  { id: 43, nameEn: "Az-Zukhruf", nameAr: "الزخرف", ayahs: 89, type: "makki" },
  { id: 44, nameEn: "Ad-Dukhan", nameAr: "الدخان", ayahs: 59, type: "makki" },
  { id: 45, nameEn: "Al-Jathiyah", nameAr: "الجاثية", ayahs: 37, type: "makki" },
  { id: 46, nameEn: "Al-Ahqaf", nameAr: "الأحقاف", ayahs: 35, type: "makki" },
  { id: 47, nameEn: "Muhammad", nameAr: "محمد", ayahs: 38, type: "madani" },
  { id: 48, nameEn: "Al-Fath", nameAr: "الفتح", ayahs: 29, type: "madani" },
  { id: 49, nameEn: "Al-Hujurat", nameAr: "الحجرات", ayahs: 18, type: "madani" },
  { id: 50, nameEn: "Qaf", nameAr: "ق", ayahs: 45, type: "makki" },
  { id: 51, nameEn: "Ad-Dhariyat", nameAr: "الذاريات", ayahs: 60, type: "makki" },
  { id: 52, nameEn: "At-Tur", nameAr: "الطور", ayahs: 49, type: "makki" },
  { id: 53, nameEn: "An-Najm", nameAr: "النجم", ayahs: 62, type: "makki" },
  { id: 54, nameEn: "Al-Qamar", nameAr: "القمر", ayahs: 55, type: "makki" },
  { id: 55, nameEn: "Ar-Rahman", nameAr: "الرحمن", ayahs: 78, type: "madani" },
  { id: 56, nameEn: "Al-Waqi'ah", nameAr: "الواقعة", ayahs: 96, type: "makki" },
  { id: 57, nameEn: "Al-Hadid", nameAr: "الحديد", ayahs: 29, type: "madani" },
  { id: 58, nameEn: "Al-Mujadila", nameAr: "المجادلة", ayahs: 22, type: "madani" },
  { id: 59, nameEn: "Al-Hashr", nameAr: "الحشر", ayahs: 24, type: "madani" },
  { id: 60, nameEn: "Al-Mumtahanah", nameAr: "الممتحنة", ayahs: 13, type: "madani" },
  { id: 61, nameEn: "As-Saff", nameAr: "الصف", ayahs: 14, type: "madani" },
  { id: 62, nameEn: "Al-Jumu'ah", nameAr: "الجمعة", ayahs: 11, type: "madani" },
  { id: 63, nameEn: "Al-Munafiqun", nameAr: "المنافقون", ayahs: 11, type: "madani" },
  { id: 64, nameEn: "At-Taghabun", nameAr: "التغابن", ayahs: 18, type: "madani" },
  { id: 65, nameEn: "At-Talaq", nameAr: "الطلاق", ayahs: 12, type: "madani" },
  { id: 66, nameEn: "At-Tahrim", nameAr: "التحريم", ayahs: 12, type: "madani" },
  { id: 67, nameEn: "Al-Mulk", nameAr: "الملك", ayahs: 30, type: "makki" },
  { id: 68, nameEn: "Al-Qalam", nameAr: "القلم", ayahs: 52, type: "makki" },
  { id: 69, nameEn: "Al-Haqqah", nameAr: "الحاقة", ayahs: 52, type: "makki" },
  { id: 70, nameEn: "Al-Ma'arij", nameAr: "المعارج", ayahs: 44, type: "makki" },
  { id: 71, nameEn: "Nuh", nameAr: "نوح", ayahs: 28, type: "makki" },
  { id: 72, nameEn: "Al-Jinn", nameAr: "الجن", ayahs: 28, type: "makki" },
  { id: 73, nameEn: "Al-Muzzammil", nameAr: "المزمل", ayahs: 20, type: "makki" },
  { id: 74, nameEn: "Al-Muddaththir", nameAr: "المدثر", ayahs: 56, type: "makki" },
  { id: 75, nameEn: "Al-Qiyamah", nameAr: "القيامة", ayahs: 40, type: "makki" },
  { id: 76, nameEn: "Al-Insan", nameAr: "الإنسان", ayahs: 31, type: "madani" },
  { id: 77, nameEn: "Al-Mursalat", nameAr: "المرسلات", ayahs: 50, type: "makki" },
  { id: 78, nameEn: "An-Naba", nameAr: "النبأ", ayahs: 40, type: "makki" },
  { id: 79, nameEn: "An-Nazi'at", nameAr: "النازعات", ayahs: 46, type: "makki" },
  { id: 80, nameEn: "Abasa", nameAr: "عبس", ayahs: 42, type: "makki" },
  { id: 81, nameEn: "At-Takwir", nameAr: "التكوير", ayahs: 29, type: "makki" },
  { id: 82, nameEn: "Al-Infitar", nameAr: "الانفطار", ayahs: 19, type: "makki" },
  { id: 83, nameEn: "Al-Mutaffifin", nameAr: "المطففين", ayahs: 36, type: "makki" },
  { id: 84, nameEn: "Al-Inshiqaq", nameAr: "الانشقاق", ayahs: 25, type: "makki" },
  { id: 85, nameEn: "Al-Buruj", nameAr: "البروج", ayahs: 22, type: "makki" },
  { id: 86, nameEn: "At-Tariq", nameAr: "الطارق", ayahs: 17, type: "makki" },
  { id: 87, nameEn: "Al-A'la", nameAr: "الأعلى", ayahs: 19, type: "makki" },
  { id: 88, nameEn: "Al-Ghashiyah", nameAr: "الغاشية", ayahs: 26, type: "makki" },
  { id: 89, nameEn: "Al-Fajr", nameAr: "الفجر", ayahs: 30, type: "makki" },
  { id: 90, nameEn: "Al-Balad", nameAr: "البلد", ayahs: 20, type: "makki" },
  { id: 91, nameEn: "Ash-Shams", nameAr: "الشمس", ayahs: 15, type: "makki" },
  { id: 92, nameEn: "Al-Layl", nameAr: "الليل", ayahs: 21, type: "makki" },
  { id: 93, nameEn: "Ad-Duha", nameAr: "الضحى", ayahs: 11, type: "makki" },
  { id: 94, nameEn: "Ash-Sharh", nameAr: "الشرح", ayahs: 8, type: "makki" },
  { id: 95, nameEn: "At-Tin", nameAr: "التين", ayahs: 8, type: "makki" },
  { id: 96, nameEn: "Al-Alaq", nameAr: "العلق", ayahs: 19, type: "makki" },
  { id: 97, nameEn: "Al-Qadr", nameAr: "القدر", ayahs: 5, type: "makki" },
  { id: 98, nameEn: "Al-Bayyinah", nameAr: "البينة", ayahs: 8, type: "madani" },
  { id: 99, nameEn: "Az-Zalzalah", nameAr: "الزلزلة", ayahs: 8, type: "madani" },
  { id: 100, nameEn: "Al-Adiyat", nameAr: "العاديات", ayahs: 11, type: "makki" },
  { id: 101, nameEn: "Al-Qari'ah", nameAr: "القارعة", ayahs: 11, type: "makki" },
  { id: 102, nameEn: "At-Takathur", nameAr: "التكاثر", ayahs: 8, type: "makki" },
  { id: 103, nameEn: "Al-Asr", nameAr: "العصر", ayahs: 3, type: "makki" },
  { id: 104, nameEn: "Al-Humazah", nameAr: "الهمزة", ayahs: 9, type: "makki" },
  { id: 105, nameEn: "Al-Fil", nameAr: "الفيل", ayahs: 5, type: "makki" },
  { id: 106, nameEn: "Quraysh", nameAr: "قريش", ayahs: 4, type: "makki" },
  { id: 107, nameEn: "Al-Ma'un", nameAr: "الماعون", ayahs: 7, type: "makki" },
  { id: 108, nameEn: "Al-Kawthar", nameAr: "الكوثر", ayahs: 3, type: "makki" },
  { id: 109, nameEn: "Al-Kafirun", nameAr: "الكافرون", ayahs: 6, type: "makki" },
  { id: 110, nameEn: "An-Nasr", nameAr: "النصر", ayahs: 3, type: "madani" },
  { id: 111, nameEn: "Al-Masad", nameAr: "المسد", ayahs: 5, type: "makki" },
  { id: 112, nameEn: "Al-Ikhlas", nameAr: "الإخلاص", ayahs: 4, type: "makki" },
  { id: 113, nameEn: "Al-Falaq", nameAr: "الفلق", ayahs: 5, type: "makki" },
  { id: 114, nameEn: "An-Nas", nameAr: "الناس", ayahs: 6, type: "makki" },
];

export function getSurah(id: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.id === id);
}

export const JUZ_BOUNDARIES: { juz: number; surah: number; ayah: number }[] = [
  { juz: 1, surah: 1, ayah: 1 },
  { juz: 2, surah: 2, ayah: 142 },
  { juz: 3, surah: 2, ayah: 253 },
  { juz: 4, surah: 3, ayah: 93 },
  { juz: 5, surah: 4, ayah: 24 },
  { juz: 6, surah: 4, ayah: 148 },
  { juz: 7, surah: 5, ayah: 82 },
  { juz: 8, surah: 6, ayah: 111 },
  { juz: 9, surah: 7, ayah: 88 },
  { juz: 10, surah: 8, ayah: 41 },
  { juz: 11, surah: 9, ayah: 93 },
  { juz: 12, surah: 11, ayah: 6 },
  { juz: 13, surah: 12, ayah: 53 },
  { juz: 14, surah: 15, ayah: 1 },
  { juz: 15, surah: 17, ayah: 1 },
  { juz: 16, surah: 18, ayah: 75 },
  { juz: 17, surah: 21, ayah: 1 },
  { juz: 18, surah: 23, ayah: 1 },
  { juz: 19, surah: 25, ayah: 21 },
  { juz: 20, surah: 27, ayah: 56 },
  { juz: 21, surah: 29, ayah: 46 },
  { juz: 22, surah: 33, ayah: 31 },
  { juz: 23, surah: 36, ayah: 28 },
  { juz: 24, surah: 39, ayah: 32 },
  { juz: 25, surah: 41, ayah: 47 },
  { juz: 26, surah: 46, ayah: 1 },
  { juz: 27, surah: 51, ayah: 31 },
  { juz: 28, surah: 58, ayah: 1 },
  { juz: 29, surah: 67, ayah: 1 },
  { juz: 30, surah: 78, ayah: 1 },
];

export function verseGlobalIndex(surah: number, ayah: number): number {
  let total = 0;
  for (let i = 1; i < surah; i += 1) {
    total += getSurah(i)?.ayahs || 0;
  }
  return total + ayah;
}

export function totalAyahs(): number {
  return SURAHS.reduce((sum, s) => sum + s.ayahs, 0);
}